apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: starcoin-runner-deployment
  namespace: actions-runner-system
spec:
  template:
    spec:
      nodeSelector:
        node-pool: ci-pool-200g
      image: ghcr.io/starcoinorg/starcoin-builder:latest
      repository: action-runner-demo/starcoin
      ephemeral: true
      tolerations:
        - key: "app"
          operator: "Equal"
          value: "ci"
          effect: "NoExecute"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-pool
                    operator: In
                    values:
                      - ci-pool-200g
      serviceAccountName: github-runner
      resources:
        requests:
          #cpu: "30.0"
          #memory: "64Gi"
          cpu: "2.0"
          memory: "4Gi"
          ephemeral-storage: "80Gi"
        limits:
          ephemeral-storage: "100Gi"
      # If set to false, there are no privileged container and you cannot use docker.
      dockerEnabled: true
      # If set to true, runner pod container only 1 container that's expected to be able to run docker, too.
      # image summerwind/actions-runner-dind or custom one should be used with true -value
      dockerdWithinRunnerContainer: false
      # Valid if dockerdWithinRunnerContainer is not true
      dockerdContainerResources:
        requests:
          #cpu: "30.0"
          #memory: "64Gi"
          cpu: "2.0"
          memory: "4Gi"
          ephemeral-storage: "80Gi"
        limits:
          ephemeral-storage: "100Gi"

---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: starcoin-runner-deployment-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: starcoin-runner-deployment
  minReplicas: 0
  maxReplicas: 3
  scaleDownDelaySecondsAfterScaleOut: 120
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - action-runner-demo/starcoin
